### ISSUE TITLE
SyntaxError: import declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by tocomo** [drien/gnome-shell-extension-clipqr#8]
JS ERROR: Extension clipqr@drien.com: SyntaxError: import declarations may only appear at top level of a module @ .local/share/gnome-shell/extensions/clipqr@drien.com/extension.js:18:0

Debian trixie
Package: gnome-shell
Version: 44.8-1

**Comment by drien** [comment]
Thanks for the report–I've built this extension against Gnome 45, so I'm not surprised that it doesn't work as expected on 44.

Making a 44-compatible release may be as simple as changing the various ESM imports to the old style (inverse of https://gjs.guide/extensions/upgrading/gnome-shell-45.html), but I'm not especially inclined to invest effort into supporting prior versions, though I'll leave this open for the time being.

**Comment by drien** [comment]
With no further requests after 500 downloads, and Gnome 46 arriving, I'm not going to look further into supporting 44.
